//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace WebJob1
{
    public class ObjectContext
    {
        private string v1;
        private string v2;

        public ObjectContext(string v1, string v2)
        {
            this.v1 = v1;
            this.v2 = v2;
        }

        internal ObjectSet<T> CreateObjectSet<T>(string v)
        {
            throw new NotImplementedException();
        }
    }
}