//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WebJob1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class lcttrainingEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new lcttrainingEntities object using the connection string found in the 'lcttrainingEntities' section of the application configuration file.
        /// </summary>
        public lcttrainingEntities() : base("name=lcttrainingEntities", "lcttrainingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new lcttrainingEntities object.
        /// </summary>
        public lcttrainingEntities(string connectionString) : base(connectionString, "lcttrainingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new lcttrainingEntities object.
        /// </summary>
        public lcttrainingEntities(EntityConnection connection) : base(connection, "lcttrainingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TrainingTable> TrainingTables
        {
            get
            {
                if ((_TrainingTables == null))
                {
                    _TrainingTables = base.CreateObjectSet<TrainingTable>("TrainingTables");
                }
                return _TrainingTables;
            }
        }
        private ObjectSet<TrainingTable> _TrainingTables;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<database_firewall_rules> database_firewall_rules
        {
            get
            {
                if ((_database_firewall_rules == null))
                {
                    _database_firewall_rules = base.CreateObjectSet<database_firewall_rules>("database_firewall_rules");
                }
                return _database_firewall_rules;
            }
        }
        private ObjectSet<database_firewall_rules> _database_firewall_rules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ipv6_database_firewall_rules> ipv6_database_firewall_rules
        {
            get
            {
                if ((_ipv6_database_firewall_rules == null))
                {
                    _ipv6_database_firewall_rules = base.CreateObjectSet<ipv6_database_firewall_rules>("ipv6_database_firewall_rules");
                }
                return _ipv6_database_firewall_rules;
            }
        }
        private ObjectSet<ipv6_database_firewall_rules> _ipv6_database_firewall_rules;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TrainingTables EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTrainingTables(TrainingTable trainingTable)
        {
            base.AddObject("TrainingTables", trainingTable);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the database_firewall_rules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodatabase_firewall_rules(database_firewall_rules database_firewall_rules)
        {
            base.AddObject("database_firewall_rules", database_firewall_rules);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ipv6_database_firewall_rules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToipv6_database_firewall_rules(ipv6_database_firewall_rules ipv6_database_firewall_rules)
        {
            base.AddObject("ipv6_database_firewall_rules", ipv6_database_firewall_rules);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lcttrainingModel", Name="database_firewall_rules")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class database_firewall_rules : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new database_firewall_rules object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="start_ip_address">Initial value of the start_ip_address property.</param>
        /// <param name="end_ip_address">Initial value of the end_ip_address property.</param>
        /// <param name="create_date">Initial value of the create_date property.</param>
        /// <param name="modify_date">Initial value of the modify_date property.</param>
        public static database_firewall_rules Createdatabase_firewall_rules(global::System.Int32 id, global::System.String name, global::System.String start_ip_address, global::System.String end_ip_address, global::System.DateTime create_date, global::System.DateTime modify_date)
        {
            database_firewall_rules database_firewall_rules = new database_firewall_rules();
            database_firewall_rules.id = id;
            database_firewall_rules.name = name;
            database_firewall_rules.start_ip_address = start_ip_address;
            database_firewall_rules.end_ip_address = end_ip_address;
            database_firewall_rules.create_date = create_date;
            database_firewall_rules.modify_date = modify_date;
            return database_firewall_rules;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                if (_name != value)
                {
                    OnnameChanging(value);
                    ReportPropertyChanging("name");
                    _name = StructuralObject.SetValidValue(value, false, "name");
                    ReportPropertyChanged("name");
                    OnnameChanged();
                }
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String start_ip_address
        {
            get
            {
                return _start_ip_address;
            }
            set
            {
                if (_start_ip_address != value)
                {
                    Onstart_ip_addressChanging(value);
                    ReportPropertyChanging("start_ip_address");
                    _start_ip_address = StructuralObject.SetValidValue(value, false, "start_ip_address");
                    ReportPropertyChanged("start_ip_address");
                    Onstart_ip_addressChanged();
                }
            }
        }
        private global::System.String _start_ip_address;
        partial void Onstart_ip_addressChanging(global::System.String value);
        partial void Onstart_ip_addressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String end_ip_address
        {
            get
            {
                return _end_ip_address;
            }
            set
            {
                if (_end_ip_address != value)
                {
                    Onend_ip_addressChanging(value);
                    ReportPropertyChanging("end_ip_address");
                    _end_ip_address = StructuralObject.SetValidValue(value, false, "end_ip_address");
                    ReportPropertyChanged("end_ip_address");
                    Onend_ip_addressChanged();
                }
            }
        }
        private global::System.String _end_ip_address;
        partial void Onend_ip_addressChanging(global::System.String value);
        partial void Onend_ip_addressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime create_date
        {
            get
            {
                return _create_date;
            }
            set
            {
                if (_create_date != value)
                {
                    Oncreate_dateChanging(value);
                    ReportPropertyChanging("create_date");
                    _create_date = StructuralObject.SetValidValue(value, "create_date");
                    ReportPropertyChanged("create_date");
                    Oncreate_dateChanged();
                }
            }
        }
        private global::System.DateTime _create_date;
        partial void Oncreate_dateChanging(global::System.DateTime value);
        partial void Oncreate_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime modify_date
        {
            get
            {
                return _modify_date;
            }
            set
            {
                if (_modify_date != value)
                {
                    Onmodify_dateChanging(value);
                    ReportPropertyChanging("modify_date");
                    _modify_date = StructuralObject.SetValidValue(value, "modify_date");
                    ReportPropertyChanged("modify_date");
                    Onmodify_dateChanged();
                }
            }
        }
        private global::System.DateTime _modify_date;
        partial void Onmodify_dateChanging(global::System.DateTime value);
        partial void Onmodify_dateChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lcttrainingModel", Name="ipv6_database_firewall_rules")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ipv6_database_firewall_rules : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ipv6_database_firewall_rules object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="start_ipv6_address">Initial value of the start_ipv6_address property.</param>
        /// <param name="end_ipv6_address">Initial value of the end_ipv6_address property.</param>
        /// <param name="create_date">Initial value of the create_date property.</param>
        /// <param name="modify_date">Initial value of the modify_date property.</param>
        public static ipv6_database_firewall_rules Createipv6_database_firewall_rules(global::System.Int32 id, global::System.String name, global::System.String start_ipv6_address, global::System.String end_ipv6_address, global::System.DateTime create_date, global::System.DateTime modify_date)
        {
            ipv6_database_firewall_rules ipv6_database_firewall_rules = new ipv6_database_firewall_rules();
            ipv6_database_firewall_rules.id = id;
            ipv6_database_firewall_rules.name = name;
            ipv6_database_firewall_rules.start_ipv6_address = start_ipv6_address;
            ipv6_database_firewall_rules.end_ipv6_address = end_ipv6_address;
            ipv6_database_firewall_rules.create_date = create_date;
            ipv6_database_firewall_rules.modify_date = modify_date;
            return ipv6_database_firewall_rules;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                if (_name != value)
                {
                    OnnameChanging(value);
                    ReportPropertyChanging("name");
                    _name = StructuralObject.SetValidValue(value, false, "name");
                    ReportPropertyChanged("name");
                    OnnameChanged();
                }
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String start_ipv6_address
        {
            get
            {
                return _start_ipv6_address;
            }
            set
            {
                if (_start_ipv6_address != value)
                {
                    Onstart_ipv6_addressChanging(value);
                    ReportPropertyChanging("start_ipv6_address");
                    _start_ipv6_address = StructuralObject.SetValidValue(value, false, "start_ipv6_address");
                    ReportPropertyChanged("start_ipv6_address");
                    Onstart_ipv6_addressChanged();
                }
            }
        }
        private global::System.String _start_ipv6_address;
        partial void Onstart_ipv6_addressChanging(global::System.String value);
        partial void Onstart_ipv6_addressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String end_ipv6_address
        {
            get
            {
                return _end_ipv6_address;
            }
            set
            {
                if (_end_ipv6_address != value)
                {
                    Onend_ipv6_addressChanging(value);
                    ReportPropertyChanging("end_ipv6_address");
                    _end_ipv6_address = StructuralObject.SetValidValue(value, false, "end_ipv6_address");
                    ReportPropertyChanged("end_ipv6_address");
                    Onend_ipv6_addressChanged();
                }
            }
        }
        private global::System.String _end_ipv6_address;
        partial void Onend_ipv6_addressChanging(global::System.String value);
        partial void Onend_ipv6_addressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime create_date
        {
            get
            {
                return _create_date;
            }
            set
            {
                if (_create_date != value)
                {
                    Oncreate_dateChanging(value);
                    ReportPropertyChanging("create_date");
                    _create_date = StructuralObject.SetValidValue(value, "create_date");
                    ReportPropertyChanged("create_date");
                    Oncreate_dateChanged();
                }
            }
        }
        private global::System.DateTime _create_date;
        partial void Oncreate_dateChanging(global::System.DateTime value);
        partial void Oncreate_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime modify_date
        {
            get
            {
                return _modify_date;
            }
            set
            {
                if (_modify_date != value)
                {
                    Onmodify_dateChanging(value);
                    ReportPropertyChanging("modify_date");
                    _modify_date = StructuralObject.SetValidValue(value, "modify_date");
                    ReportPropertyChanged("modify_date");
                    Onmodify_dateChanged();
                }
            }
        }
        private global::System.DateTime _modify_date;
        partial void Onmodify_dateChanging(global::System.DateTime value);
        partial void Onmodify_dateChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="lcttrainingModel", Name="TrainingTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TrainingTable : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TrainingTable object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static TrainingTable CreateTrainingTable(global::System.Int32 id)
        {
            TrainingTable trainingTable = new TrainingTable();
            trainingTable.Id = id;
            return trainingTable;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TrainingName
        {
            get
            {
                return _TrainingName;
            }
            set
            {
                OnTrainingNameChanging(value);
                ReportPropertyChanging("TrainingName");
                _TrainingName = StructuralObject.SetValidValue(value, true, "TrainingName");
                ReportPropertyChanged("TrainingName");
                OnTrainingNameChanged();
            }
        }
        private global::System.String _TrainingName;
        partial void OnTrainingNameChanging(global::System.String value);
        partial void OnTrainingNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TrainingProvider
        {
            get
            {
                return _TrainingProvider;
            }
            set
            {
                OnTrainingProviderChanging(value);
                ReportPropertyChanging("TrainingProvider");
                _TrainingProvider = StructuralObject.SetValidValue(value, true, "TrainingProvider");
                ReportPropertyChanged("TrainingProvider");
                OnTrainingProviderChanged();
            }
        }
        private global::System.String _TrainingProvider;
        partial void OnTrainingProviderChanging(global::System.String value);
        partial void OnTrainingProviderChanged();

        #endregion

    }

    #endregion

}
